### ISSUE TITLE
[v8] margin/padding of page container on mobile devices

### ISSUE THREAD

**Issue by unarist** [MasterDalK/kktCSS#26]
We introduced `.status`-like styles for /about, but it will also bring an extra margin/padding.

For example (iPhone 6 size):

Original | kktCSS
------- | ------
![image](https://cloud.githubusercontent.com/assets/705555/25337411/bdd81246-2936-11e7-9bbb-1cc8f7ffb174.png) | ![image](https://cloud.githubusercontent.com/assets/705555/25337425/c9b01ac8-2936-11e7-9795-268d33b2c421.png)

Removing example:

Before | After
------- | ------
![image](https://cloud.githubusercontent.com/assets/705555/25337425/c9b01ac8-2936-11e7-9795-268d33b2c421.png) | ![image](https://cloud.githubusercontent.com/assets/705555/25337668/bbca998c-2937-11e7-87ff-83879c4f85a0.png)

(BTW, "Kirakiratter" is bit longer than "Mastodon", so the logo and the site title can't be in the same line on iPhone 5 size anyway)

Same issue occurs in user page and status page, but I don't know it should be fixed or not.

Original | kktCSS
------- | ------
![image](https://cloud.githubusercontent.com/assets/705555/25338239/7484d112-2939-11e7-9640-5713881f46d0.png) | ![image](https://cloud.githubusercontent.com/assets/705555/25338205/5a562f34-2939-11e7-8388-db2523768c2a.png)

**Comment by bit-map** [comment]
I definitely think the extra margins/padding could be removed in all these cases for mobile widths.

As for the Kirakiratter logo+title breaking (it happens on my iPhone 7 as well), I think that is a separate issue, but it might be worth looking into dynamically resizing the font size to fit both on one line.
(On a related note, it would be nice to fix those line breaks in weird places (mostly in Japanese) because of the way those `<em>` tags work)

**Comment by unarist** [comment]
> On a related note, it would be nice to fix those line breaks in weird places (mostly in Japanese) because of the way those `<em>` tags work

Yeah, I will investigate it tomorrow.

**Comment by MasterDalK** [comment]
Yeah, we should definitely get rid of those extra paddings & margins for mobile.

Let us know if you find anything out about those <em>'s!
