### ISSUE TITLE
coloring of URLs in the user profile

### ISSUE THREAD

**Issue by unarist** [MasterDalK/kktCSS#27]
![image](https://cloud.githubusercontent.com/assets/705555/25340174/e2d4367a-293f-11e7-917c-967de41ec273.png)

URLs in the user profile are styled as green text with pink underline, and :hover removes the underline. But default style of it shows underline (same as text color) on :hover. Is current styling you expected?

**Comment by bit-map** [comment]
That behavior (underline/no underline being reversed for user profiles, as opposed to toots) is there in the original Mastodon, mostly because they don't color URLs, @-s, or hashtags:
![image](https://cloud.githubusercontent.com/assets/6811760/25346921/360415e4-28e7-11e7-8199-5010144f6684.png)

I think that since kktCSS does color URLs, @-s, and hashtags, it would be okay to get rid of the underline and have it show only on hover.

**Comment by unarist** [comment]
Oops, that's right.

Yes, I think that is good either...

- no specific color + underline default, or
- specific color + underline on :hover

and I think line color should be same as text.

**Comment by bit-map** [comment]
If I had to choose, I think option 2, specific color + underline on :hover, looks nicer.

As for the fact that the text and underline colors are different for regular URLs (in both toots and profiles), that was a decision @MasterDalK made a while ago, but I wouldn't mind opening it up for discussion again (although there aren't many contributors to have said discussion with in the first place).

**Comment by unarist** [comment]
> the text and underline colors are different for regular URLs (in both toots and profiles)

Really? I've intended to my suggestion is same as toots, so...maybe I should take a sleep first...

**Comment by bit-map** [comment]
Currently, it is:
- URLs in toots: Green, no underline → Green, pink underline on hover
- URLs in profile: Green, pink underline → Green, no underline on hover

So if you want to make the underline color match the text (both green) for URLs in profiles, then we should do the same for URLs in toots. I think making the underline colors the same for both is a viable route as well.

**Comment by MasterDalK** [comment]
I got it backwards on profiles by accident, was supposed to be no underline regular, then pink underline on hover.

I just thought it looked cute with the underline colour being different (also because it was possible to do so with the way mastodon is coded). If people think it should be same colour text & underline, we can do that.
The about page is same colour text & underline because it's not possible to do it there.

**Comment by unarist** [comment]
I see. and I might be confused with the toot timestamp and the notification sender, which has green underline:

(below image shows all underlines with devtool)

![image](https://cloud.githubusercontent.com/assets/705555/25369675/951a38ea-29c0-11e7-97ca-8a7917574d1b.png)

Well, I will fix hover problem in this time.

**Comment by MasterDalK** [comment]
Yeah, I meant for "important" links to have the pink underline. Helps separate things in my opinion.
