### ISSUE TITLE
[RFC] Where should we have a follow/unfollow button?

### ISSUE THREAD

**Issue by unarist** [MasterDalK/kktCSS#69]
Currently we have a follow button on beneath the column header, i.e. the back button. This sometimes incur accidentally click on the follow button instead of the back button.

![image](https://cloud.githubusercontent.com/assets/705555/26284113/af2955b4-3e6e-11e7-8bec-781339a01353.png)

Adding confirmation to follow/unfollow action also may be good, but, I think it should be moved somewhere, like on the right side. I've also moved followed indicator to the left side to avoid conflict.

![image](https://cloud.githubusercontent.com/assets/705555/26284158/a4b601d0-3e6f-11e7-86d1-6b4cbfc46032.png)

(This is also upstream issue, actually)

**Comment by bit-map** [comment]
You can also think about it the opposite way: instead of having the back button on the left side for profile and detailed status thread views, moving it to the right side, like for local/federated/favourites/follow requests/muted users/blocked users, might be better for consistency (perhaps with a descriptive title), and then the current placement of follow/unfollow button and followed indicator can stay.

Well, if you decide to go that route, it becomes an issue of more than just the CSS though...

**Comment by MasterDalK** [comment]
I think swapping left/right positions would be good. Follow button is on the right on Twitter too.
